//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Chairs
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Chair leg.
    /// </summary>
    //  *** Start programmer edit section *** (ChairLeg CustomAttributes)

    //  *** End programmer edit section *** (ChairLeg CustomAttributes)
    [AutoAltered()]
    [Caption("Chair leg")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ChairLegE", new string[] {
            "Number as \'Number\'"})]
    public class ChairLeg : ICSSoft.STORMNET.DataObject
    {
        
        private int fNumber;
        
        private IIS.Chairs.Chair fChair;
        
        //  *** Start programmer edit section *** (ChairLeg CustomMembers)

        //  *** End programmer edit section *** (ChairLeg CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        //  *** Start programmer edit section *** (ChairLeg.Number CustomAttributes)

        //  *** End programmer edit section *** (ChairLeg.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                //  *** Start programmer edit section *** (ChairLeg.Number Get start)

                //  *** End programmer edit section *** (ChairLeg.Number Get start)
                int result = this.fNumber;
                //  *** Start programmer edit section *** (ChairLeg.Number Get end)

                //  *** End programmer edit section *** (ChairLeg.Number Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ChairLeg.Number Set start)

                //  *** End programmer edit section *** (ChairLeg.Number Set start)
                this.fNumber = value;
                //  *** Start programmer edit section *** (ChairLeg.Number Set end)

                //  *** End programmer edit section *** (ChairLeg.Number Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Chairs.Chair.
        /// </summary>
        //  *** Start programmer edit section *** (ChairLeg.Chair CustomAttributes)

        //  *** End programmer edit section *** (ChairLeg.Chair CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Chairs.Chair Chair
        {
            get
            {
                //  *** Start programmer edit section *** (ChairLeg.Chair Get start)

                //  *** End programmer edit section *** (ChairLeg.Chair Get start)
                IIS.Chairs.Chair result = this.fChair;
                //  *** Start programmer edit section *** (ChairLeg.Chair Get end)

                //  *** End programmer edit section *** (ChairLeg.Chair Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ChairLeg.Chair Set start)

                //  *** End programmer edit section *** (ChairLeg.Chair Set start)
                this.fChair = value;
                //  *** Start programmer edit section *** (ChairLeg.Chair Set end)

                //  *** End programmer edit section *** (ChairLeg.Chair Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ChairLegE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ChairLegE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ChairLegE", typeof(IIS.Chairs.ChairLeg));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ChairLeg.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfChairLeg CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfChairLeg CustomAttributes)
    public class DetailArrayOfChairLeg : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Chairs.DetailArrayOfChairLeg members)

        //  *** End programmer edit section *** (IIS.Chairs.DetailArrayOfChairLeg members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ChairLeg by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ChairLeg.
        /// </summary>
        public DetailArrayOfChairLeg(IIS.Chairs.Chair fChair) : 
                base(typeof(ChairLeg), ((ICSSoft.STORMNET.DataObject)(fChair)))
        {
        }
        
        public IIS.Chairs.ChairLeg this[int index]
        {
            get
            {
                return ((IIS.Chairs.ChairLeg)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Chairs.ChairLeg dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
