//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Chairs
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Chair type.
    /// </summary>
    //  *** Start programmer edit section *** (ChairType CustomAttributes)

    //  *** End programmer edit section *** (ChairType CustomAttributes)
    [AutoAltered()]
    [Caption("Chair type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ChairTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("ChairTypeL", new string[] {
            "Name as \'Name\'"})]
    public class ChairType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (ChairType CustomMembers)

        //  *** End programmer edit section *** (ChairType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (ChairType.Name CustomAttributes)

        //  *** End programmer edit section *** (ChairType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (ChairType.Name Get start)

                //  *** End programmer edit section *** (ChairType.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (ChairType.Name Get end)

                //  *** End programmer edit section *** (ChairType.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ChairType.Name Set start)

                //  *** End programmer edit section *** (ChairType.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (ChairType.Name Set end)

                //  *** End programmer edit section *** (ChairType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ChairTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ChairTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ChairTypeE", typeof(IIS.Chairs.ChairType));
                }
            }
            
            /// <summary>
            /// "ChairTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ChairTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ChairTypeL", typeof(IIS.Chairs.ChairType));
                }
            }
        }
    }
}
